---
# tasks file for openldap
- name: "Include Default OS variables if custom ones are not provided on the host_vars of IdP"
  include_vars: "{{ ansible_os_family }}.yml"
  tags: openldap

- name: "Install openLDAP"
  import_tasks: ldap-install.yml
  tags: openldap

- name: "Configure openLDAP"
  import_tasks: ldap-configure.yml
  tags: openldap

- name: "Restore openLDAP"
  import_tasks: ldap-restore.yml
  tags: openldap

- name: "Start OpenLDAP"
  systemd: 
   name: slapd
   daemon-reload: True
   state: started
   enabled: True
  tags: openldap
